# name = input("Введите Ваше имя: ")
# print (type (name))
# current_year = 2024
# date_of_birth = int(input("В каком году Вы родились? "))
# age = current_year - date_of_birth
# print("Здравствуйте, ", name)
# print("В этом году Вам ", age, "лет")
#print('привет я строка в нижнем регистре' .upper().replace('ПРИВЕТ', 'пока'))
my_string = input("Сколько букв в Вашем имени?")
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])